{{- if not .Values.backend.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cicd-analyzer.fullname" . }}-backend
  labels:
    {{- include "cicd-analyzer.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
